name: build

on:
  push:
    branches: 
      - master
      
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.15.0
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.0'
    - name: Install yarn and run unittest
      run: |
        yarn
        yarn test
      env:
        CI: true
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ethergru/devops-app/devops-app
        registry: docker.pkg.github.com
        username: ${{ secrets.MY_GITHUB_USERNAME }}
        password: ${{ secrets.MY_GITHUB_TOKEN }}
        dockerfile: Dockerfile.prod
        tags: prod
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
        MY_GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        host: ${{ secrets.MY_HOST }}
        username: ${{ secrets.MY_USERNAME }}
        password: ${{ secrets.MY_PASSWORD }}
        port: ${{ secrets.MY_PORT }}
        envs: MY_GITHUB_USERNAME, MY_GITHUB_TOKEN
        script: |
          docker stop $(docker ps -a -q)
          docker login docker.pkg.github.com -u $MY_GITHUB_USERNAME -p $MY_GITHUB_TOKEN
          docker pull docker.pkg.github.com/ethergru/devops-app/devops-app:prod
          docker run -dit -p 80:80 docker.pkg.github.com/ethergru/devops-app/devops-app:prod