name: build

on:
  push:
    branches: 
      - master
      
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.15.0
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.0'
    - name: Install yarn and run unittest
      run: |
        yarn
        yarn test
      env:
        CI: true
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ethergru/hubbers-new-admn/hubbers-admin
        registry: docker.pkg.github.com
        username: ${{ secrets.MY_GITHUB_USERNAME }}
        password: ${{ secrets.MY_GITHUB_TOKEN }}
        dockerfile: Dockerfile.prod
        tags: latest
